### ISSUE TITLE
stealing is buggy

### ISSUE THREAD

**Issue by soumith** [burnson/StealThisPiece#1]
Trying to Steal a piece, I get:

http://stealthispiece.com/queue.php

ERROR

The request could not be satisfied.

This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests. 
Generated by cloudfront (CloudFront)
Request ID: UcDN7InDcsI0C6VqyOLs6LUugOAuCx85annV_iEiTYYVCRPjm4BoSA==

**Comment by soumith** [comment]
oh, nevermind. didn't see that this is a 2012 project.

**Comment by burnson** [comment]
Yeah, the website needs a revamp to make this work again. The GitHub repository only has the C++ code to the music generator. May be a good time to use emscripten...
